version: 0.0
os: linux

files:
  - source: target/ROOT.war
    destination: /home/ec2-user

hooks:
  AfterInstall:
    - location: scripts/install_and_deploy_tomcat.sh
      timeout: 300
      runas: ec2-user

