version: 0.2

env:
  variables:
    ARTIFACT_BUCKET: "tomcat-bucket-test"      # ✅ your S3 bucket name
    ARTIFACT_PATH: "build-artifacts/"          # ✅ optional S3 prefix path

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven...
      - yum install -y maven

  pre_build:
    commands:
      - echo Checking Maven version...
      - mvn --version

  build:
    commands:
      - echo Building the Java WAR package...
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo Build complete. Verifying artifact...
      - ls -l target/
      - |
        ARTIFACT_FILE=$(ls target/*.war | head -n 1)
        if [ -z "$ARTIFACT_FILE" ]; then
          echo "❌ No WAR file found in target/ — exiting"
          exit 1
        fi
        echo "✅ Found artifact: $ARTIFACT_FILE"
        echo "Uploading to s3://$ARTIFACT_BUCKET/$ARTIFACT_PATH"
        aws s3 cp "$ARTIFACT_FILE" "s3://$ARTIFACT_BUCKET/$ARTIFACT_PATH"
      - echo "✅ Artifact pushed to s3://$ARTIFACT_BUCKET/$ARTIFACT_PATH"

artifacts:
  files:
    - target/*.war
    - appspec.yml
    - scripts/install_and_deploy_tomcat.sh
  
